apiVersion: apps/v1
kind: Deployment
metadata:
  name: DrawingClassifiers
  labels:
    app: workbench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workbench-DrawingClassifiers
  template:
    metadata:
      labels:
        app: workbench-DrawingClassifiers
    spec:
      containers:
      - name: DrawingClassifiers
        image:
        ports:
        - containerPort: 3000
        #livenessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: 3000
        #  initialDelaySeconds: 2
        #  periodSeconds: 2
        #readinessProbe:
        #  httpGet:
        #    path: /healthz
        #    port: 3000
        #  initialDelaySeconds: 2
        #  periodSeconds: 2
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: DrawingClassifiers
  labels:
    app: workbench
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: workbench-DrawingClassifiers

