stages:
  - build
  - deploy

variables:
  TAG: latest #$CI_COMMIT_SHORT_SHA
  IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_PATH_SLUG:$TAG

build:
  only:
    refs:
      - master
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG -f build/package/Dockerfile .
    - docker push $IMAGE_TAG

deploy to staging:
  only:
    refs:
      - master
  stage: deploy
  environment:
    name: staging
    kubernetes:
      namespace: fid-bau-staging
  image: dtzar/helm-kubectl
  script:
    - kubectl apply -f deployments/kubernetes.yaml
    - kubectl rollout restart deployment/floorplan-classifier
